import React from "react";
import Head from "next/head";
function about() {
  return (
    <div>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h2>About</h2>
    </div>
  );
}

export default about;
