import Head from "next/head";
import Header from "../components/Header";
import AritclesList from "../components/AritclesList";

export default function Home({ aritcles }) {
  return (
    <div>
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <AritclesList ariticles={aritcles} />
    </div>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=20`
  );
  const aritcles = await res.json();

  return {
    props: {
      aritcles,
    },
  };
};
